-- Sample data for check_engine database
-- This script creates a complete example workflow from appointment to invoice

USE check_engine_db;

-- 1. Insert TipoServicio (Service Types)
INSERT INTO tipo_servicio (nombre, descripcion, tarifaBase) VALUES
('Cambio de aceite y filtro', 'Cambio de aceite motor y filtro de aceite', 35.00),
('Revisión de frenos', 'Inspección completa del sistema de frenos', 25.00),
('Alineación y balanceo', 'Alineación de ruedas y balanceo de neumáticos', 40.00),
('Diagnóstico computarizado', 'Escaneo y diagnóstico de códigos de error OBD2', 30.00),
('Cambio de pastillas de freno', 'Reemplazo de pastillas de freno delanteras o traseras', 45.00);

-- 2. Insert Repuesto (Parts/Spare Parts)
INSERT INTO repuesto (codigo, descripcion, categoria, stockActual, stockMinimo, precioUnitario) VALUES
('REP-000001', 'Filtro de aceite 5W-30', 'FILTROS', 25, 5, 8.50),
('REP-000002', 'Aceite sintético 5W-30 (galón)', 'LUBRICANTES', 15, 3, 28.00),
('REP-000003', 'Pastillas de freno delanteras', 'FRENOS', 12, 4, 65.00),
('REP-000004', 'Pastillas de freno traseras', 'FRENOS', 10, 4, 55.00),
('REP-000005', 'Líquido de frenos DOT 4', 'LIQUIDOS', 20, 5, 12.00),
('REP-000006', 'Discos de freno delanteros (par)', 'FRENOS', 6, 2, 120.00),
('REP-000007', 'Bujías (juego de 4)', 'ENCENDIDO', 8, 3, 35.00),
('REP-000008', 'Filtro de aire', 'FILTROS', 18, 5, 15.00);

-- 3. Insert Cita (Appointment)
-- Note: Using existing cliente_id = 1 and vehiculo_id = 1
INSERT INTO cita (fechaHora, estado, comentarios, cliente_id, vehiculo_id) VALUES
('2025-12-05 09:00:00', 'ATENDIDA', 'Cliente reporta luces de advertencia en el tablero y ruido al frenar', 1, 1);

-- Get the cita_id that was just created (assuming it's 1 for this example)
SET @cita_id = LAST_INSERT_ID();

-- 4. Insert OrdenServicio (Service Order)
-- Note: year, numero, and codigo will be auto-generated by @PrePersist
-- We need to insert with manual values first, then the system will manage them automatically
-- For manual insertion, we'll set them directly
INSERT INTO orden_servicio (year, numero, codigo, fechaCreacion, fechaCierre, diagnosticoInicial, observaciones, estadoActual, cita_id, vehiculo_id) VALUES
(2025, 1, 'OS-2025-00001', '2025-12-05', NULL,
'Vehículo presenta luz de check engine encendida. Código P0171 - Sistema muy pobre (Banco 1). También se detecta desgaste en pastillas de freno delanteras y líquido de frenos bajo nivel.',
'Cliente autoriza trabajos. Se ordenaron repuestos necesarios.',
'EN_REPARACION', @cita_id, 1);

SET @orden_id = LAST_INSERT_ID();

-- 5. Insert DetalleTrabajoOrden (Work Details)
INSERT INTO detalle_trabajo_orden (horas, tarifaHora, subtotal, tipo_servicio_id, orden_servicio_id) VALUES
-- Diagnóstico computarizado: 1 hora a $30/hora
(1.0, 30.00, 30.00,
    (SELECT id FROM tipo_servicio WHERE nombre = 'Diagnóstico computarizado'),
    @orden_id),
-- Cambio de aceite y filtro: 0.5 horas a $35/hora
(0.5, 35.00, 17.50,
    (SELECT id FROM tipo_servicio WHERE nombre = 'Cambio de aceite y filtro'),
    @orden_id),
-- Cambio de pastillas de freno: 1.5 horas a $45/hora
(1.5, 45.00, 67.50,
    (SELECT id FROM tipo_servicio WHERE nombre = 'Cambio de pastillas de freno'),
    @orden_id),
-- Revisión de frenos: 0.5 horas a $25/hora
(0.5, 25.00, 12.50,
    (SELECT id FROM tipo_servicio WHERE nombre = 'Revisión de frenos'),
    @orden_id);

-- 6. Insert DetalleRepuestoOrden (Parts Used)
INSERT INTO detalle_repuesto_orden (cantidad, precioUnitario, subtotal, repuesto_id, orden_servicio_id) VALUES
-- Filtro de aceite: 1 unidad a $8.50
(1, 8.50, 8.50,
    (SELECT id FROM repuesto WHERE codigo = 'REP-000001'),
    @orden_id),
-- Aceite sintético: 1 galón a $28.00
(1, 28.00, 28.00,
    (SELECT id FROM repuesto WHERE codigo = 'REP-000002'),
    @orden_id),
-- Pastillas de freno delanteras: 1 juego a $65.00
(1, 65.00, 65.00,
    (SELECT id FROM repuesto WHERE codigo = 'REP-000003'),
    @orden_id),
-- Líquido de frenos: 1 unidad a $12.00
(1, 12.00, 12.00,
    (SELECT id FROM repuesto WHERE codigo = 'REP-000005'),
    @orden_id),
-- Filtro de aire: 1 unidad a $15.00
(1, 15.00, 15.00,
    (SELECT id FROM repuesto WHERE codigo = 'REP-000008'),
    @orden_id);

-- 7. Update stock in repuesto table (decrease stock for used parts)
UPDATE repuesto SET stockActual = stockActual - 1 WHERE codigo = 'REP-000001';
UPDATE repuesto SET stockActual = stockActual - 1 WHERE codigo = 'REP-000002';
UPDATE repuesto SET stockActual = stockActual - 1 WHERE codigo = 'REP-000003';
UPDATE repuesto SET stockActual = stockActual - 1 WHERE codigo = 'REP-000005';
UPDATE repuesto SET stockActual = stockActual - 1 WHERE codigo = 'REP-000008';

-- 8. Insert FacturaInterna (Internal Invoice)
-- Note: The @PrePersist method will auto-generate numero and calculate totals
-- For manual insertion, we calculate:
-- Subtotal Mano de Obra: 30.00 + 17.50 + 67.50 + 12.50 = $127.50
-- Subtotal Repuestos: 8.50 + 28.00 + 65.00 + 12.00 + 15.00 = $128.50
-- Subtotal General: $256.00
-- IVA (15%): $38.40
-- Total: $294.40

INSERT INTO factura_interna (year, numeroSecuencial, numero, fechaEmision, subtotalManoObra, subtotalRepuestos, porcentajeIVA, iva, total, orden_servicio_id) VALUES
(2025, 1, 'FACT-2025-00001', '2025-12-09', 127.50, 128.50, 15.00, 38.40, 294.40, @orden_id);

-- Display summary
SELECT '=== RESUMEN DE DATOS CREADOS ===' as '';
SELECT CONCAT('Cliente: ', nombres, ' ', apellidos, ' (Cédula: ', cedula, ')') as 'CLIENTE' FROM cliente WHERE id = 1;
SELECT CONCAT('Vehículo: ', marca, ' ', modelo, ' ', anio, ' (Placa: ', placa, ')') as 'VEHICULO' FROM vehiculo WHERE id = 1;
SELECT CONCAT('Tipos de Servicio creados: ', COUNT(*)) as 'SERVICIOS' FROM tipo_servicio;
SELECT CONCAT('Repuestos creados: ', COUNT(*)) as 'REPUESTOS' FROM repuesto;
SELECT CONCAT('Cita: ', DATE_FORMAT(fechaHora, '%Y-%m-%d %H:%i'), ' - Estado: ', estado) as 'CITA' FROM cita WHERE id = @cita_id;
SELECT CONCAT('Orden de Servicio: ', codigo, ' - Estado: ', estadoActual) as 'ORDEN' FROM orden_servicio WHERE id = @orden_id;
SELECT CONCAT('Detalles de Trabajo: ', COUNT(*), ' - Total: $', SUM(subtotal)) as 'MANO_DE_OBRA' FROM detalle_trabajo_orden WHERE orden_servicio_id = @orden_id;
SELECT CONCAT('Detalles de Repuestos: ', COUNT(*), ' - Total: $', SUM(subtotal)) as 'REPUESTOS_USADOS' FROM detalle_repuesto_orden WHERE orden_servicio_id = @orden_id;
SELECT CONCAT('Factura: ', numero, ' - Total: $', total, ' (IVA 15%: $', iva, ')') as 'FACTURA' FROM factura_interna WHERE orden_servicio_id = @orden_id;
